using Problems.Interfaces;

namespace Problems.Excercises1To10
{
    public class Problem002 : Problem, IProblem1To10
    {
        public string Name()
        {
            return "Problem002: Even Fibonacci numbers";
        }

        public string Description()
        {
            return @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

                    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
        }

        public AnswerDTO Run()
        {
            StartTimer();
            
            var sum = 0;
            var previous = 1;
            var current = 2;

            while (current < 4000000)
            {
                if (IsEven(current))
                {
                    sum += current;
                }
                
                var temp = current;
                current = previous + current;
                previous = temp;
            }
            
            return new AnswerDTO {Answer = sum.ToString(), TimeTaken = StopTimer().ToString()};
        }

        private bool IsEven(int current)
        {
            return current % 2 == 0;
        }

        public int Number()
        {
            return 2;
        }
    }
}